project:
  type: website
  output-dir: docs

website:
  favicon: favicon.png
  open-graph:
    locale: en_US
  title: "Bell's CSCI 0451 Blog"
  navbar:
    pinned: true
    right:
      - about.qmd
      - icon: github
        href: https://github.com/doabell/451-blog
      - icon: file-earmark-person
        href: https://rpubs.com/yluo

format:
  html:
    toc: true
    smooth-scroll: true
    html-math-method: katex
    title-block-banner: img/nate-watson-IN3pV9rH1a8-unsplash.jpg
    title-block-banner-color: white
    theme:
      light:
        - flatly
        - override.scss
        - light.scss
      dark: 
        - darkly
        - override.scss
        - dark.scss
    css: styles.css





