project:
  type: website
  output-dir: docs

website:
  title: "Bell's CSCI 0451 Blog"
  navbar:
    background: "#112a39"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/doabell/451-blog
      - icon: file-earmark-person
        href: https://rpubs.com/yluo

format:
  html:
    title-block-banner: img/nate-watson-IN3pV9rH1a8-unsplash.jpg
    title-block-banner-color: white
    theme: cosmo
    css: styles.css





